version: "3"

volumes:
  postgres_data:
      driver: local
services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bff_app
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432